trigger:
- master

variables:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true

jobs:

- job: Mac
  pool:
    vmImage: 'macOS-10.14'

  steps:
  - task: UseDotNet@2
    displayName: Install .NET Core 3.1 SDK
    inputs:
      version: '3.1.x'
      packageType: sdk

  - script: dotnet test test/Spreads.BLAS.Tests.NuGet/Spreads.BLAS.Tests.NuGet.csproj -f netcoreapp3.0 -c Release -v m
    displayName: 'Test netcoreapp3.0'

- job: Linux
  pool:
    vmImage: 'ubuntu-16.04'

  steps:
  - task: UseDotNet@2
    displayName: Install .NET Core 3.1 SDK
    inputs:
      version: '3.1.x'
      packageType: sdk

  - script: dotnet test test/Spreads.BLAS.Tests.NuGet/Spreads.BLAS.Tests.NuGet.csproj -f netcoreapp3.0 -c Release -v m
    displayName: 'Test netcoreapp3.0'

- job: Windows
  pool:
    vmImage: 'vs2017-win2016'

  steps:
  - task: UseDotNet@2
    displayName: Install .NET Core 3.1 SDK
    inputs:
      version: '3.1.x'
      packageType: sdk

  - script: dotnet test test/Spreads.BLAS.Tests.NuGet/Spreads.BLAS.Tests.NuGet.csproj -f netcoreapp3.0 -c Release -v m
    displayName: 'Test netcoreapp3.0'